# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  tests:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            /home/circleci/.pyenv/versions/3.10.4/bin/python3.10 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Test with pytest
          command: pytest -Wi

  build_and_push_to_docker_hub:
    docker:
      - image: cimg/python:3.10.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PWD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container and push to docker hub
          command: |
            docker build -t oc-lettings .
            docker tag oc-lettings:latest $DOCKERHUB_USER/oc-lettings:$CIRCLE_SHA1
            echo "$DOCKERHUB_PWD" | docker login -u $DOCKERHUB_USER --password-stdin
            docker push $DOCKERHUB_USER/oc-lettings:$CIRCLE_SHA1

  deploy_to_heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a oc-lettings2389 web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a oc-lettings2389 web

workflows:
  "test_build_push_deploy":
    jobs:
      - tests
      - build_and_push_to_docker_hub:
          requires:
            - tests
          filters:
            branches:
              only: main
      - deploy_to_heroku:
          requires:
            - build_and_push_to_docker_hub
          filters:
            branches:
              only: main
