# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  tests:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            /home/circleci/.pyenv/versions/3.10.4/bin/python3.10 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Test with pytest
          command: pytest -Wi

  build_and_push_to_docker_hub:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container and push to docker hub
          uses: docker/login-action@v1
            with:
              username: ${{DOCKER_USER.DOCKERHUB_USERNAME}}
              password: ${{DOCKER_USER.DOCKERHUB_PASSWORD}}
          command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              docker build -t oc-lettings .
              docker tag oc-lettings:latest maxf2389/oc-lettings:$CIRCLE_SHA1
              docker login -u maxf2389 --password dockerhub
              docker push maxf2389/oc-lettings:$CIRCLE_SHA1
            fi

workflows:
  "test_build_push":
    jobs:
      - tests
      - build_and_push_to_docker_hub:
          requires:
            - tests
